TCM:
  enable: true
  description: "进群欢迎"
  author: "Kanwuqing"
  version: "1.0.0"
  cmd: '中药'

  prescription:
    桂枝汤: 桂枝15克, 白芍15克, 甘草10克, 生姜15克, 红枣20克
    葛根汤: 葛根6克, 麻黄3克, 桂枝3克, 芍药6克, 甘草3克
    桂枝加葛根汤: 葛根12克, 桂枝6克, 芍药6克, 炙甘草5克, 生姜9克, 大枣3枚
    栝蒌桂枝汤: 栝楼根6克、桂枝9克、芍药9克、甘草6克、生姜9克、大枣3枚
    柴胡桂枝汤: 桂枝4.5克
    小建中汤: 芍药18克，桂枝9克，炙甘草6克，生姜10克，大枣4枚，饴糖30克
    桂枝二越婢一汤: 桂枝去皮，十八铢(2.3g);芍药十八铢(2.3g);麻黄十八铢(2.3g);甘草炙，十八铢(2.3g);大枣擘，四枚;生姜切，一两二铢(3.3g);石膏碎，绵裹，一两(3g)
    麻桂各半汤: 桂枝5克（去皮）芍药 生姜（切）甘草（炙）麻黄（去节）各3克 大枣4枚（擘）杏仁（汤浸，去皮、尖及两仁者）24枚
    当归四逆汤: 当归12g、桂枝9g、芍药9g、细辛3g、炙甘草6g、通草6g、大枣8枚
    当归四逆加吴茱萸生姜汤: 当归9克 芍药9克 甘草6克（炙）通草3克 桂枝9克（去皮）细辛1.5克 生姜15克（切）吴茱萸5克 大枣5枚（擘）
    桂枝加龙骨牡蛎汤: 桂枝三两(9克)、芍药三两(9克)、生姜三两(9克)、甘草二两(6克)、 大枣十二枚(12枚)、龙骨三两(9克)、牡蛎三两(9克)
    芍药汤: 芍药一两 (30g)， 当归半两 (15g) ，黄连半两 (15g) ，槟榔、木香、甘草炒各二钱 (各6g)， 大黄三钱 (9g) ，黄芩半两 (15g)， 官桂二钱半 (5g)
    桂枝加大黄汤: 桂枝三两 (9克)、白芍药六两 (12克)、生姜三两 (9克)、大黄二两 (6克)、大枣十二枚 (3枚)、甘草二两 (6克)
    桂枝附子汤: 桂枝四两 (9克)、附子三枚 (9克)、炙甘草二两 (6克)、生姜三两 (9克)、大枣十二枚 (9克)
    桂枝加附子汤: 桂枝15克, 白芍15克, 灸甘草15克, 生姜15克, 红枣20克, 附子10克
    葛根汤加川芎辛夷: 葛根12、麻黄9、桂枝6、白芍6、川芎6、辛夷6(包)、炙甘草6、生姜3片、大枣3枚
    桂枝加黄耆汤: 桂枝 芍药 甘草各6克 生姜9克 大枣12枚 黄耆6克
    越婢加术附汤: 麻黄12g、石膏24g、生姜9g、甘草6g、白术12g、大枣十五枚
    越婢加术汤: 麻黄18克，石膏45—100克，生姜9克，大枣5枚，炙甘草6克，白术12克
    越婢汤: 麻黄六两(18克)、石膏半斤(24克)、生姜三两(9克)、甘草二两(6克)、大枣十五枚(5枚)
    大青龙汤: 麻黄六两 (12克)、桂枝二两 (6克)、甘草二两 (6克)、杏仁四十粒 (6克)、石膏如鸡子大 (18克)、生姜三两 (9克)、大枣十二枚 (3枚)
    小青龙汤: 麻黄9克，芍药9克，细辛3克，干姜3克，炙甘草6克，桂枝6克，半夏9克，五味子3克
    麻杏薏甘汤: 火麻仁6g，杏仁10个，去皮尖炒6g，甘草炙3g，薏苡仁12g
    续命汤: 人参、甘草（炙）、 干姜 、麻黄（去节）、独活、当归、川芎、石膏（碎，绵裹）各二两，附子（炮）一枚，桂心、白术、细辛各三分，防风五分，芍药二分，秦艽一两，杏仁（去两仁尖皮）四十枚，黄芩一两
    麻黄连轺赤小豆汤: 麻黄6克（去节）连轺6克（即连翘根）杏仁6克 赤小豆10克 大枣12枚（擘）生梓白皮（切）10克 生姜6克 甘草6克（炙）
    葛根汤加桔梗石膏: 柴胡15克, 黄芩15克, 半夏10克, 党参10克, 葛根30克, 麻黄10克, 桂枝10克, 白芍10克, 生石膏30克, 桔梗10克, 连翘15克, 生姜10克, 大枣5枚, 生草6克
    麻黄汤: 麻黄9g、桂枝6g、杏仁6g、炙甘草3g
    越婢加半夏汤: 麻黄六两（18g），石膏半斤（24g），生姜三两（9g），大枣十五枚，甘草二两（6g），半夏半升（12g）
    麻杏甘石汤: 麻黄6g杏仁9g石膏24g炙甘草6g
    厚朴麻黄汤: 厚朴五两（15g），麻黄四两（12g），石膏（如鸡子大）（30g~60g），五味子、杏仁、半夏各半升（15g），干姜、细辛各二两（6g），小麦一升（30g）
    当归芍药散: 当归三两(9克)，芍药一斤(30克)，泽泻、川芎半斤(15克)，茯苓、白术四两(12克)
    苓桂术甘汤: 茯苓四两(12g)桂枝去皮，三两(9g) 白术二两(6g) 甘草炙，二两(6g)
    柴苓汤: 柴胡、白茯苓、甘草、陈皮、防风、白芍（炒）、当归身、白术（炒）
    五苓散: 猪苓9g、泽泻15g、白术9g、茯苓9g、桂枝6g
    猪苓汤: 猪苓、茯苓、阿胶、泽泻、滑石，各二钱半
    茵陈五苓散: 茵陈五两三钱(160克)、泽写一两(30克)、猪苓三钱(9克)、茯苓三钱(9克) 、白术三钱(9克)、桂心二钱(6克)
    胃苓汤: 苍术、陈皮、厚朴、茯苓、猪苓、泽泻、官桂、白术、甘草
    茯苓泽泻汤: 茯苓40g、泽泻30g、甘草20g、桂枝15g、白术15g、生姜30g、黄芪30g、党参20g、升麻12g、陈皮20g
    柴胡桂枝干姜汤: 柴胡3钱，甘草2钱，人参1钱，茯苓3钱，桂枝3钱，干姜3钱
    大柴胡汤: 厚朴24g，甘草9g，大黄9g，大枣十枚，枳实12g，桂枝6g，生姜15g
    小柴胡汤: 半夏（汤洗七次.焙干）二两半，柴胡（去芦）半斤，人参、甘草（炙）、黄芩，各三两
    柴陷汤: 柴胡12g，黄芩9g，半夏9g，生姜9g，人参6g，大枣4枚，甘草（炙）5g
    柴胡加龙骨牡蛎汤: 柴胡12克 龙骨 黄芩 生姜 铅丹 人参 桂枝(去皮)茯苓各4.5克 半夏6克(洗)大黄6克(切)牡蛎4.5克(熬)大枣(擘)6枚
    小柴胡汤加桔梗石膏: 半夏（汤洗七次.焙干）二两半，柴胡（去芦）半斤，人参、甘草（炙）、黄芩，各三两, 桔梗9克
    甘草泻心汤: 甘草12克 (炙) 黄芩 9克 干姜9克 半夏9克 (洗) 大枣 12枚 (擘) 黄连3克
    生姜泻心汤: 生姜12克(切) 、甘草9克(炙) 、人参9克 、干姜3克、 黄芩9克、 半夏9克(洗)、 黄连3克 、大枣12枚(擘)
    半夏泻心汤: 半夏15g，黄芩、干姜、人参、炙甘草各9g，黄连3g，大枣4枚

  tree: 
    桂枝汤:
      q: 发热吗?(有/没有)
      有:
        q: 头部后颈有牵扯不适的感觉吗?(有/没有)
        有:
          q: 全身酸痛吗?(酸痛/不酸痛)
          酸痛:
            q: 平时有汗吗?(有/没有)
            有: 桂枝加葛根汤
            没有: 葛根汤
          不酸痛:
            q: 痉(挛), 角弓反张, 即头和下肢后弯, 躯干向前; 或是怕风/自发性出汗吗?(痉症/恶风有汗)
            痉症: 栝蒌桂枝汤
            恶风有汗: 桂枝汤
        没有:
          q: 平时体力体质好吗?(好/不好)
          好:
            q: 咽炎, 咽部难受; 或是自觉怕冷, 哪怕加衣服靠近暖气也不见好, 且同时发热?(咽炎/恶寒发热)
            咽炎: 桂枝二越婢一汤
            恶寒发热: 麻桂各半汤
          不好:
            q: 有时自觉怕冷, 哪怕加衣服靠近暖气也不见好, 有时发热; 或是肚子疼, 食欲不振?(往来寒热/腹痛)
            往来寒热: 柴胡桂枝汤
            腹痛: 小建中汤
      没有:
        q: 肚子疼吗?(疼/不疼)
        疼:
          q: 怕冷但是可通过穿衣服等操作缓解吗?(是/不是)
          是:
            q: 唾液多; 或是身体局部气血不通, 胸闷/手脚冷/痉(挛), 角弓反张, 即头和下肢后弯, 躯干向前等?(唾液多/气血不通)
            唾液多: 当归四逆加吴茱萸生姜汤
            气血不通: 当归四逆汤
          不是:
            q: 失眠吗?(有/没有)
            有: 桂枝加龙骨牡蛎汤
            没有:
              q: 肚子胀; 或是便秘?(肚子胀/便秘)
              肚子胀: 桂枝加芍药汤
              便秘: 桂枝加大黄汤
        不疼:
          q: 怕冷但是可通过穿衣服等操作缓解吗?(是/不是)
          是:
            q: 心烦; 或是小便困难, 四肢活动受限?(心烦/小便困难)
            心烦: 桂枝附子汤
            小便困难: 桂枝加附子汤
          不是:
            q: 有鼻涕, 较浓, 可能还会流到咽部; 或是皮肤表面有水肿, 有黄色的汗?(鼻涕/黄汗)
            鼻涕: 葛根汤加川芎辛夷
            黄汗: 桂枝加黄耆汤
  
    麻黄汤:
      q: 有水肿吗?(有/没有)
      有:
        q: 口渴吗?(口渴/不口渴)
        口渴:
          q: 便秘吗?(有/没有)
          有:
            q: 四肢骨节痛, 水肿; 或是上半身水肿严重, 下肢关节略肿, 尿量少?(水肿/少尿)
            水肿:
              越婢加术附汤
            少尿:
              越婢加术汤
          没有:
            q: 关节肌肉酸痛僵直活动受限, 身体肿; 或是发热且怕冷, 穿上衣服也不见好, 不出汗但是烦躁?(风湿/恶寒烦躁)
            风湿:
              越婢汤
            恶寒烦躁:
              大青龙汤
        不口渴:
          q: 咳嗽吗?(有/没有)
          有:
            q: 流清水鼻涕, 咳痰严重; 或是风湿关节肿痛, 发热在下午3:00~5:00加剧?(鼻涕/关节肿痛)
            鼻涕:
              小青龙汤
            关节肿痛:
              麻杏薏甘汤
          没有:
            q: 半身不遂, 瘫痪; 或是小便黄, 不思饮食, 发热且浑身发冷或穿上衣服也不见好, 无汗身体痒?(半身不遂/发热恶寒)
            半身不遂:
              续命汤
            发热恶寒:
              麻黄连轺赤小豆汤
      没有:
        q: 感冒吗?(有/没有)
        有:
          q: 肌肉疼痛吗?(有/没有)
          有:
            q: 有头部后颈有牵扯不适的感觉, 且黄痰浓鼻涕; 或是痉(挛), 角弓反张, 即头和下肢后弯, 躯干向前, 没有汗, 容易受风等的刺激?(黄痰/无汗)
            黄痰:
              葛根汤加桔梗石膏
            无汗:
              葛根汤
          没有:
            q: 有荨麻疹, 风疹; 或是发热且怕冷, 穿上衣服也不见好, 头痛身体疼, 没有汗, 容易喘气?(荨麻疹/发热恶寒)
            荨麻疹:
              麻桂各半汤
            发热恶寒:
              麻桂各半汤
        没有:
          q: 一直有痰; 或是容易咳出脓痰; 或是没有痰?(一直有痰/容易有痰/没有痰)
          一直有痰:
            越婢加半夏汤
          容易有痰:
            q: 发热且咳喘(有)
            有:
              麻杏甘石汤
          没有痰:
            q: 胃胀, 咳嗽容易喘; 或是发热怕冷, 穿上衣服怕冷也不见好, 发热较多, 怕冷较少?(胃胀/恶寒发热)
            胃胀:
              厚朴麻黄汤
            恶寒发热:
              桂枝二越婢一汤
    
    五苓散:
      q: 头晕吗?(晕/不晕)
      晕:
        q: 改变身体姿势时眩晕?(是/不是)
        是:
          q: 面色白, 血虚; 或是气短, 呼吸不畅?(血虚/气短)
          血虚:
            当归芍药散
          气短:
            苓桂术甘汤
        不是:
          q: 咳嗽, 心悸, 口苦, 眩晕等; 或是口渴, 小便不利?(柴胡症/口渴)
          柴胡症:
            柴苓汤
          口渴:
            五苓散
      不晕:
        q: 尿血, 小便不利, 尿痛?(有/没有)
        有:
          猪苓汤
        没有:
          q: 黄疸, 身体发黄?(有/没有)
          有:
            茵陈五苓散
          没有:
            q: 喜欢干燥, 受不了潮湿, 腹胀; 或是反胃, 吐了之后口渴想喝水; 或是呕吐, 咳嗽喘气，不能平卧，浮肿多见于面部，痰沫多而色白, 呕吐后想喝水?(燥湿健脾/反胃/隔)
            燥湿健脾:
              胃苓汤
            反胃:
              茯苓泽泻汤
            膈:
              猪苓散
    
    葛根汤:
      q: 咽喉舒服吗?(是/不是)
      是:
        q: 黄鼻涕; 或是无汗, 全身痛, 头部后颈有牵扯不适的感觉?(黄鼻涕/无汗)
        黄鼻涕:
          葛根汤加桔梗石膏
        无汗:
          葛根汤
      不是:
        q: 全身痛; 或是鼻涕多, 鼻炎, 鼻窦炎; 或是肠道声音响, 腹泻, 呕吐?(全身痛/鼻炎/腹泻)
        全身痛:
          桂枝加葛根汤
        鼻炎:
          葛根汤加川芎辛夷
        腹泻:
          葛根加半夏汤

    小柴胡汤:
      q: 发烧怕冷交替吗?(有/没有)
      有:
        q: 心脏跳动加快或不规则?(有/没有)
        有:
          q: 怕冷, 且穿衣后也不见好; 或是口渴且小便不利?(恶寒/小便不利)
          恶寒:
            q: 疾病延缓不愈, 渴但是不呕吐, 头上有汗; 或是四肢疼痛, 心脏不舒服?(头上有汗/四肢疼痛)
            头上有汗: 
              柴胡桂枝干姜汤
            四肢疼痛:
              柴胡桂枝汤
          小便不利:
            柴苓汤
        没有:
          q: 胃部感觉涨, 按压时感觉硬且满?(有/没有)
          有:
            大柴胡汤
          没有:
            q: 胀痛, 气都聚集在胸中; 或是口苦、咽干、目眩、往来寒热、胸胁苦满、默默不欲饮食、心烦喜呕?(胀痛/心烦喜呕)
            胀痛:
              柴陷汤
            心烦喜呕:
              小柴胡汤
      没有:
        q: 嘴巴干吗?(有/没有)
        有:
          q: 不易入睡; 或是小孩高烧不退, 喉咙痛?(失眠/喉咙痛)
          失眠:
            柴胡加龙骨牡蛎汤
          喉咙痛:
            小柴胡汤加桔梗石膏
        没有:
          q: 黏膜(如口腔黏膜)充血, 糜烂, 溃疡?(有/没有)
          有:
            小甘草泻心汤
          没有:
            q: 打嗝; 或是想呕吐(打嗝/呕吐)
            打嗝:
              生姜泻心汤
            呕吐:
              半夏泻心汤
